[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
nft_minter = "8vt2EUt8A2zpepJe8AbghFUa6eHgRCoGNreiETsRGcfS"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/seb/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[package]
name = "nft_storage"
version = "0.1.0"
authors = ["VotreNom <votre-email@example.com>"]

[dependencies]
solana-program = "1.18.17"

 


 
